mongodb-js/hadron-build

- commands/release.js
The read-installed module is not able to distinguish devDependencies from dependendies, but since we "npm install --production" during our build process, just point to that directory.
Seem reasonable?
> INT-696 LICENSE: Include only production dependencies

- commands/release.js
Latest hadron-build stops executing at the version write task since the callback is never executed. Same happens on the license file write.
> Writing license and version must execute done callback.

- commands/test.js
- test/index.test.js
Can be run now with --packages passed through. For example from Compass:
```bash
npm test -- --packages
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/hadron-build/8)
> Provide ability to run only package tests:

- lib/config.js
- test/config.test.js
Currently, hadron-build assumes that channel can only be one of `stable`, `dev`, `beta`. We can relax this assumption and only differ between `stable` and all other branches, e.g. `world`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/hadron-build/10)
> remove assumption of channel names (namely `beta`)

- lib/config.js
- test/config.test.js
This way beta and stable will have their own install paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/hadron-build/11)
> INT-1491: :bug: :checkered_flag: nuget name should include channel

- commands/ui.js
- lib/config.js
Adjust positions of Icons for new background DMG image. 
Note: In order not to affect older builds, we should bump the major version here to avoid accidentally rolling this change forward, or we need to backport the new DMG backgrounds to at least 1.4.0 (we probably won't be building 1.3.x versions anymore).
Ideally, this would not be hard-coded here though but Compass would set it in its package.json `build` key.
> COMPASS-179 new background

- package.json
Introduced in 073a0918, this breaks tests in Compass.
> Reverting the upgrade of yargs to 6.3.0

- commands/upload.js
Latest Github API (http://mikedeboer.github.io/node-github/) was backkwards breaking as of 6.x. This updates the upload tasks to the latest API. cc/ @imlucas
> Fix Github upload

- package.json
If an app has specifically defined an electron-prebuilt version such as
`1.2.8`, having hadron-build require `^1.4.12` would cause unexpected
behavior. The app in this case would be compiling native add-on’s
targeting the abi for `1.2.8` and they would suddenly start to fail as
`hadron-build develop` would use `1.4.12` which is abi incompatible.
> Enable dedupe'ing electron-prebuilt

- lib/config.js
- package.json
- test/config.test.js
- test/release.test.js
Our upstreams could potentially use npm’s platform requirement (e.g.
`electron-installer-debian` just won’t install on windows). Moving them
to `optionalDependencies` and inlining the `require()` calls for them
inline means we can be graceful and test thoroughly on any platform.
> Make platform specific dependencies optional

- lib/target.js
Trying [this suggestion from
electron-packager](https://github.com/electron-userland/electron-package
r/issues/396#issuecomment-264730685).
```
[2016/12/28 16:06:55.515]     at Error (native)
[2016/12/28 16:06:55.515]   errno: -36,
[2016/12/28 16:06:55.515]   code: 'ENAMETOOLONG',
[2016/12/28 16:06:55.515]   syscall: 'unlink',
[2016/12/28 16:06:55.515]   path:
'/data/mci/c5ff319993fa42af0c87ceed59d4feac/src/electron-packager/linux-
x64…
```
> Avoid ENAMETOOLONG on rhel

- README.md
- commands/test.js
- package.json
- test/fixtures/hadron-app/src/internal-packages/index.js
- test/fixtures/hadron-app/test/enzyme/index.test.js
- test/fixtures/hadron-app/test/functional/index.test.js
- test/fixtures/hadron-app/test/main/index.test.js
- test/fixtures/hadron-app/test/renderer/index.test.js
- test/fixtures/hadron-app/test/unit/index.test.js
- test/index.test.js
Introducing test suites:
- `unit`: Fast unit tests of individual functions / methods
- `enzyme`: React component tests using the [Enzyme](https://github.com/airbnb/enzyme) framework
- `packages`: Tests specified in the `./src/internal-packages` folders (mostly unit and enzyme tests)
- `main`: Electron-specific tests run in the main process
- `renderer`: Electron-specific tests run in the renderer process
- `functional`: Slow functional test using [Spectron](https://github.com/electron/spectron) (launches the application)
Test suites are run in their own process each, with the correct arguments. For example, renderer tests require the `--renderer` flag, packages tests require `--recursive`.
> COMPASS-648 reorganize test folder structure. 

- commands/verify.js
- package.json
This fixes installing Compass for development on Windows 10:
BEFORE
AFTER
> Drop check-python to fix Windows dev install

- package.json
This pull request pins our `electron-winstaller` dependency at the `2.5.1` release from mid-December 2016 and is known good.  This fixes Compass' Windows builds (see [evergreen results](https://evergreen.mongodb.com/task/10gen_compass_master_windows_compile_cafb3d091be686d9f36bd84447bc2c88abebe866_17_03_01_16_47_13)).
On Jan 25th, [Squirrel.Windows added dll and node files to the list of artifacts `--releasify` attempts to codesign](https://github.com/Squirrel/Squirrel.Windows/commit/d37e20042ea04b132f05a80a6b186878ac26f375). On Jan. 26th, Compass Windows builds started failing for an unknown reason. I've back-tracked this to the `electron-winstaller` 2.5.2 release on the same day, which included [the `--releasify` changes from Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows …
> COMPASS-748: Fix Windows

- commands/release.js
- package.json
- test/fixtures/hadron-app/package.json
- test/fixtures/hadron-app/src/app/index.html
- test/release.test.js
Release command takes an optional distribution as an argument but defaults to `compass-lite` for backwards compatibility for the time being.
`hadron-build release compass-enterprise`.
The style manager will go through the configured packages and compile their index.less stylesheets and then inject them into the index.html. For backwards compatibility also reads from the packages configured styles names.
> COMPASS-914: Style manager puts styles in head during release

- lib/target.js
@durran or @imlucas would you mind explaining why we need to do this? Ticket seems straightforward enough.
> COMPASS-1044 - Make libsecret a dependency for debian

- lib/target.js
- test/config.test.js
- test/fixtures/hadron-app/package.json
Anything longer than 27 characters will trigger an error in appdmg.
> COMPASS-1019 - Truncate dmg names on macosx

- README.md
- commands/test.js
- test/index.test.js
It never worked properly, workaround in Compass is to put tests into the top level tests folder, or better yet to convert the plugin to an external plugin.
> COMPASS-704 Remove packages option

- lib/target.js
make sure users know they need to install `gnome-keyring` on linux flavours.
> add gnome-keyring as a requirement for both debian and rpm OSs

- package-lock.json
- package.json
Rollback `electron-winstaller` to `2.5.1` for now. Don't upgrade until [BUILD-2932](https://jira.mongodb.org/browse/BUILD-2932) is done.
* Fixes COMPASS-4127 
* Answers BUILD-10250
[Evergreen windows builds](https://evergreen.mongodb.com/task/10gen_compass_master_windows_package_and_publish_compass_3d7b0895c3d7ed4aada6f997286a8a57d7f835b5_20_01_31_17_33_22) started failing with the electron 6 update:
```
[2020/01/31 12:47:29.021] ×  Error: Error: Failed with exit code: 4294967295
--
[2020/01/31 12:47:29.021] Output:
[2020/01/31 12:47:29.021] System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: '.\signtool.exe sign yes C:\Users\mci-exec\AppData\Local\SquirrelTemp\tempa\lib\net45\ffmpeg.dll'
[2020/01/31 12:47:29.021]    at …
```
> COMPASS-4127: Rollback electron-winstaller to 2.5.1

- lib/target.js
This way it’s easier to keep them out of the debug log in CI.
> COMPASS-4077 - Allow loading Apple notarization credentials from file

- commands/release.js
Electron apps might depend on npm hooks to e.g., rebuild their native modules on postinstall to match electron version. As the plugin installs dependencies from scratch during packaging (not just copying them over from source), scripts should be preserved so hooks can run properly
> Keep scripts so that hooks can correctly run when packaging

- commands/release.js
- lib/target.js
We would need to unpack new compass shell runtime with all its dependencies for it to work correctly, for that reason this PR adds an ability to extend/override asar create options using hadron config
> feat: Allow to override asar options during the build
